---
- hosts: do
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Clone/pull project repo
      git: repo={{ repo_url }} dest={{ root_dir }} accept_hostkey=yes

    - name: Make directory tree readable
      file:
        path: "{{ root_dir }}"
        mode: u=rwX,g=rX,o=rX
        recurse: yes
        owner: "{{ user_acc }}"
        group: www-data

    - name: build blog
      command: "{{ hugo_binary }}" chdir=yes

    - name: Update nginx config
      template: 
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ project_name }}.conf
      notify: nginx restart

    - name: Symlink nginx conf
      file: 
        src: /etc/nginx/sites-available/{{ project_name }}.conf
        dest: /etc/nginx/sites-enabled/{{ project_name }}.conf
        state: link
      notify: nginx restart

    - name: make sure nginx server is running
      service: name=nginx state=started enabled=yes

  handlers:
    - name: nginx restart
      service: name=nginx state=restarted
